/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    pub fn pass(
        grid: *const ::std::os::raw::c_int,
        goal_x: ::std::os::raw::c_int,
        goal_y: ::std::os::raw::c_int,
        rows: ::std::os::raw::c_int,
        cols: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
