[package]
name = "boiler_plate"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
aoc_cli = { version = "0.1.0", path = "../aoc_cli" }
log = "0.4.22"
serde = "1.0.216"
serde_linewise = { version = "0.1.0", path = "../serde_linewise" }
