/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    pub fn wrap(
        Ax: *mut ::std::os::raw::c_int,
        Bx: *mut ::std::os::raw::c_int,
        Ay: *mut ::std::os::raw::c_int,
        By: *mut ::std::os::raw::c_int,
        Tx: *mut ::std::os::raw::c_int,
        Ty: *mut ::std::os::raw::c_int,
        size: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
